AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BlipKey:
    Type: String
  BlipUri:
    Type: String
  DbConnectionUrl:
    Type: String

Description: '

  VWCO Chatbot Blip AWS resources

  '
Globals:
  Function:
    Timeout: 20
Resources:
  BlipEventsDatamartIntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BlipEventsDatamartIntegrationFunction
      Handler: br.com.vwco.chatbot.blip.datamart.integration.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          BLIP_KEY:            
            Fn::Sub: "Key dndjb3YyOjR0SFZKdlRjR3FqbE1hbDd6RlVR"
          BLIP_URI:            
            Fn::Sub: "https://http.msging.net/commands"
          DB_CONNECTION_URL:            
            Fn::Sub: "jdbc:sqlserver://database.cy4ibmqxejb7.us-east-1.rds.amazonaws.com:1433;databaseName=optest;user=admin;password=password123"
      Policies:
        - S3FullAccessPolicy:
            BucketName: blip-test
      Events:
        BlipEventsDatamartIntegration:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /execute
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlipEventsDatamartIntegrationApi:
    Description: "API Gateway endpoint URL for Prod stage for BlipEventsDatamartIntegration function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BlipEventsDatamartIntegrationFunction:
    Description: "BlipEventsDatamartIntegration Function ARN"
    Value: !GetAtt BlipEventsDatamartIntegrationFunction.Arn
  BlipEventsDatamartIntegrationFunctionIamRole:
    Description: "Implicit IAM Role created for BlipEventsDatamartIntegration function"
    Value: !GetAtt BlipEventsDatamartIntegrationFunctionRole.Arn
